### ISSUE TITLE
Concerns regarding the new License paragraph with Toyota

### ISSUE THREAD

**Issue by sergidomenechguzy** [ShenhanQian/GaussianAvatars#10]
In a recent commit you updated the license and added a new paragraph about Toyota Motor Europe NV/SA.

I am currently working on my masters thesis and wanted to use this project to generate gaussian splatting human heads that i can use in my own project. According to the [Creative Commons Attribution-NonCommercial-ShareAlike 4.0](https://github.com/ShenhanQian/GaussianAvatars/blob/main/LICENSE.md) license you are using, I should be allowed to use and even make custom changes to this project for non commercial use if I use the same license and attribute the original authors.

But the separate Toyota paragraph explicitly says:
> Toyota Motor Europe NV/SA and its affiliated companies retain all intellectual property and proprietary rights in and to this software, related documentation and any modifications thereto. Any use, reproduction, disclosure or distribution of this software and related documentation without an express license agreement from Toyota Motor Europe NV/SA is strictly prohibited.

Could you clarify how these two contradicting parts work together? Am I allowed to use it according to the Creative Commons license or is the use and reproduction prohibited without a separate license from Toyota and all my possible modifications would be intellectual property of Toyota.

**Comment by ShenhanQian** [comment]
Hi, thanks for the question!

Toyota only owns the current software, not the possible modifications.
You can use and modify the code as long as you do it for non-commercial purposes.

We have updated the license paragraphs to avoid confusion.

**Comment by sergidomenechguzy** [comment]
Perfect, thank you so much for the quick response and updated license!
