### ISSUE TITLE
Don't find simple-knn.

### ISSUE THREAD

**Issue by DuanWei1234** [ShenhanQian/GaussianAvatars#13]
Hello, I try to configure this code environment, but can not find the submodule simple-knn's page.

**Comment by ShenhanQian** [comment]
Hi, did you clone the repository with `--recursive`?

As instructed in the installation commands, a complete line should be:
```
git clone https://github.com/ShenhanQian/GaussianAvatars.git --recursive
```

**Comment by DuanWei1234** [comment]
OK, thank you for your reply, I successfully adjustment the problem through your solution. I just downlaod the code from the webpage, the URL may be run.
