### ISSUE TITLE
About pre-processed data

### ISSUE THREAD

**Issue by ZiaChen** [ShenhanQian/GaussianAvatars#14]
I have applied for and obtained the pre-processed data authentication, but when trying to verify the code on OneDrive sent via email, the email delay is too long and the verification code has expired. I have tried multiple times to solve the issue without success. Is there any other way to obtain the pre-processed data?

**Comment by ShenhanQian** [comment]
What was the email address you used for the data request? If you have other email accounts, we can permit them.

**Comment by ZiaChen** [comment]
I have sent you an email. Thank you for your answer!

**Comment by ShenhanQian** [comment]
Already added your alternative email. Please try again.

**Comment by ZiaChen** [comment]
I am now able to verify and receive the verification code. Thank you for your assistance.
