### ISSUE TITLE
Triangles for the upper and lower teeth

### ISSUE THREAD

**Issue by RainbowRui** [ShenhanQian/GaussianAvatars#17]
What a great job! Congratulation for CVPR's acceptance! I find your paper described that

> We also manually add triangles for the upper and lower teeth, which are rigid to the neck and jaw joints, respectively.

Would you plan to share the revised FLAME mesh in the future? It is quite important for me! Thanks a lot!

**Comment by ShenhanQian** [comment]
Thanks for your attention!

We don't have a revise template mesh. Instead, we add the teeth triangles when creating a FLAME object. You can refer to this function:
https://github.com/ShenhanQian/GaussianAvatars/blob/76038ba8908d5bb3719bfec4d5ef68bf71a5a6a0/flame_model/flame.py#L184

**Comment by RainbowRui** [comment]
Thanks! I will take a try!
