### ISSUE TITLE
COLMAP reading bug

### ISSUE THREAD

**Issue by ramazan793** [ShenhanQian/GaussianAvatars#19]
I get the following error while trying to train the model on custom COLMAP data:
`CameraInfo.__new__() got an unexpected keyword argument 'image'`

Apparently, you forgot to comment out passing an image argument when instantiating `CameraInfo` in `readColmapCameras()`

UPD:
Other arguments, such as background, timestep and camera_id are also missing:
`TypeError: CameraInfo.__new__() missing 3 required positional arguments: 'bg', 'timestep', and 'camera_id'`

UPD2:
Looks like interfaces have been changed, since `SceneInfo` is also missing arguments while working with COLMAP:
`TypeError: SceneInfo.__new__() missing 5 required positional arguments: 'val_cameras', 'train_meshes', 'test_meshes', 'tgt_train_meshes', and 'tgt_test_meshes'`

**Comment by ShenhanQian** [comment]
Thanks for reporting the issues!

The data loading functions for COLMAP data are directly inherited from GaussianSpatting. They are outdated; thus, errors are expected. 

You could update the interface for COLMAP data by mimicking our default interface for a "DynamicNerf" dataset.

**Comment by 3Der1999** [comment]
Sorry to interrupt. Have you solved the problem？ @ramazan793

**Comment by ShenhanQian** [comment]
We have added support for COLMAP datasets for static scenes via recent commits. You should be able to run datasets like MipNeRF360 within our code base. It should be easier to apply your custom datasets for head avatars then.
