### ISSUE TITLE
about customize dataset

### ISSUE THREAD

**Issue by tianxiaguixin002** [ShenhanQian/GaussianAvatars#2]
Dear author:
1. How to make customize data for generate our own head avatar?
2. Does it support mono video data for input? just like IMavatar data format, NeRSemble data use 16 calibrated camera, which is difficult to build such professional equipment, but mono video data can capture from a mobile phone.

Looking forward to your reply ， thank you!

**Comment by boh95** [comment]
I have the same problems too.

**Comment by ShenhanQian** [comment]
We plan to share the pre-processing code after the paper is accepted. Please stay in tuned.

**Comment by Tiandishihua** [comment]
> We plan to share the pre-processing code after the paper is accepted. Please stay in tuned.

Congratulations on your CVRP papers. Can you share the preprocessing data code as soon as possible?

**Comment by jryebread** [comment]
@ShenhanQian any update on when the pre-processing code might be released?

**Comment by Yifever20002** [comment]
Any Update?

**Comment by Yifever20002** [comment]
Hope it coming soon...

**Comment by int33** [comment]
@ShenhanQian Congratulations on CVPR Highlight!!! Would preprocessing data code still be released?

**Comment by ShenhanQian** [comment]
We have released a head tracking repository: https://github.com/ShenhanQian/VHAP. 
It is not the same as the original tracker, but the output can be directly used by GaussianAvatars.
