### ISSUE TITLE
How to get 3d landmarks?

### ISSUE THREAD

**Issue by ShaYito** [ShenhanQian/GaussianAvatars#20]
I am new to this area so this question may be stupid. 
I checked out the facial landmark detector "Star loss: Reducing semantic ambiguity in facial landmark detection." as you mentioned in appendix A. It gives a set of 2D landmarks for an image. 
How could we get 3D landmarks to fit a FLAME mesh?
Thanks for your time!

**Comment by ShenhanQian** [comment]
You don't have to use a 3D landmark detector. You can project 3D points on FLAME to 2D and minimize the error with the predicted 2D landmarks from STAR.
