### ISSUE TITLE
GaussianAvatars-Local Viewer problem

### ISSUE THREAD

**Issue by scnu-yyyyjx** [ShenhanQian/GaussianAvatars#22]
Hello, I encountered an error when using the **GaussianAvatars-Local Viewer** in your project for model preview. When I try to resize the window, the program crashes with the error: "**Segmentation fault (core dumped).**" How can I resolve this issue? I am running Ubuntu 20.04.

**Comment by ShenhanQian** [comment]
Hi, thanks for reporting this bug! We also met this problem when running the remote viewer on a local PC with Ubuntu 22.04.

The problem arises from [here](https://github.com/ShenhanQian/GaussianAvatars/blob/76038ba8908d5bb3719bfec4d5ef68bf71a5a6a0/remote_viewer.py#L510-L524). It is a callback function that we implemented to support window resizing under the framework of DearPyGui. 

This function works fine on:
- Windows on a local PC
- WSL (Windows Subsystem for Linux) on a local PC
- Ubuntu on a remote server with X11 support

But it crashed on:
- Ubuntu 22.04 on a local PC

We haven't figured out a solution.

A workaround is that you launch the viewer with your desired resolution by adding arguments `--H height --W width` or changing the default window size [here](https://github.com/ShenhanQian/GaussianAvatars/blob/76038ba8908d5bb3719bfec4d5ef68bf71a5a6a0/remote_viewer.py#L37-L40).

Meanwhile, please don't hesitate to share with us if you find a way to fix the resizing problem for a local Ubuntu.

**Comment by scnu-yyyyjx** [comment]
> Hi, thanks for reporting this bug! We also met this problem when running the remote viewer on a local PC with Ubuntu 22.04.
> 
> The problem arises from [here](https://github.com/ShenhanQian/GaussianAvatars/blob/76038ba8908d5bb3719bfec4d5ef68bf71a5a6a0/remote_viewer.py#L510-L524). It is a callback function that we implemented to support window resizing under the framework of DearPyGui.
> 
> This function works fine on:
> 
>     * Windows on a local PC
> 
>     * WSL (Windows Subsystem for Linux) on a local PC
> 
>     * Ubuntu on a remote server with X11 support
> 
> 
> But it crashed on:
> 
>     * Ubuntu 22.04 on a local PC
> 
> 
> We haven't figured out a solution.
> 
> A workaround is that you launch the viewer with your desired resolution by adding arguments `--H height --W width` or changing the default window size [here](https://github.com/ShenhanQian/GaussianAvatars/blob/76038ba8908d5bb3719bfec4d5ef68bf71a5a6a0/remote_viewer.py#L37-L40).
> 
> Meanwhile, please don't hesitate to share with us if you find a way to fix the resizing problem for a local Ubuntu.

Thank you for your reply

**Comment by xz0305** [comment]
Hello, the data is now available. I encountered the following two problems during the visualization process. Have you encountered these problems?
1. Glfw Error 65543: GLX: Failed to create context: GLXBadFBConfig
python:/home/runner/work/DearPyGui/DearPyGui/thirdparty/glfw/src/window.c:533: glfwSetWindowPos: Assertion `window != NULL' failed.

2. X Error of failed request: BadAlloc (insufficient resources for operation)
   Major opcode of failed request: 146 (GLX)
   Minor opcode of failed request: 5 (X_GLXMakeCurrent)
   Serial number of failed request: 0
   Current serial number in output stream: 29

**Comment by xz0305** [comment]
> Hello, the data is now available. I encountered the following two problems during the visualization process. Have you encountered these problems?
> 
> 1. Glfw Error 65543: GLX: Failed to create context: GLXBadFBConfig
>    python:/home/runner/work/DearPyGui/DearPyGui/thirdparty/glfw/src/window.c:533: glfwSetWindowPos: Assertion `window != NULL' failed.
> 2. X Error of failed request: BadAlloc (insufficient resources for operation)
>    Major opcode of failed request: 146 (GLX)
>    Minor opcode of failed request: 5 (X_GLXMakeCurrent)
>    Serial number of failed request: 0
>    Current serial number in output stream: 29

Solved this problem by using Windows

**Comment by ShenhanQian** [comment]
> Hello, the data is now available. I encountered the following two problems during the visualization process. Have you encountered these problems?
> 
> 1. Glfw Error 65543: GLX: Failed to create context: GLXBadFBConfig
>    python:/home/runner/work/DearPyGui/DearPyGui/thirdparty/glfw/src/window.c:533: glfwSetWindowPos: Assertion `window != NULL' failed.
> 2. X Error of failed request: BadAlloc (insufficient resources for operation)
>    Major opcode of failed request: 146 (GLX)
>    Minor opcode of failed request: 5 (X_GLXMakeCurrent)
>    Serial number of failed request: 0
>    Current serial number in output stream: 29

You can check if X11 and OpenGL libraries are correctly set up by running `xeyes` and `glxgears` on Linux.
Our viewer should work when the above two programs work.
