### ISSUE TITLE
Regarding Camera Information

### ISSUE THREAD

**Issue by yc4ny** [ShenhanQian/GaussianAvatars#25]
Thank you very much for this open source work. 
I wanted to ask about the cameras used for capturing the raw data in the NeRSemble dataset. 
I think I've found a model (Sony Atlas 7.1 MP Model) which seems like the one you guys used but wanted to make sure.
Thanks.

**Comment by tobias-kirschstein** [comment]
Hi,
Yes that is the cameras that were used for the recording. Manufactured by Lucidvision

**Comment by yc4ny** [comment]
Thanks for the reply!
