### ISSUE TITLE
About the color loss in Appendix A. FLAME Tracking 

### ISSUE THREAD

**Issue by ShaYito** [ShenhanQian/GaussianAvatars#26]
I am implementing the "FLAME Tracking" described in Appendix A. And I have a small question about the color loss.
Do you use texture space [FLAMETex](https://github.com/HavenFeng/photometric_optimization/blob/master/models/FLAME.py#L220) provided by authors of FLAME, or use mesh uv generator such as `xatlas` to generate a customized texture?
Thanks for your time in advance.

**Comment by ShenhanQian** [comment]
We use the texture space of FLAME as an initialization and optimize the texture map during tracking to better capture the appearance of the subject.

**Comment by ShaYito** [comment]
Thank you!
