### ISSUE TITLE
Length of Training data

### ISSUE THREAD

**Issue by sstzal** [ShenhanQian/GaussianAvatars#27]
Hi，
I have a question about the training data. Looking forward to your reply.

How many frames were used in your experiments during training a head avatar?
I have conducted some experiments based on the original GS and found that using more frames for training leads to worse results. Do you have any suggestions as to why this is happening?

**Comment by ShenhanQian** [comment]
Hi, we use 1k-2k timesteps with 15 views to optimize an avatar. 

According to my past experiments, more frames should contribute to better or at least comparable results unless face tracking is inaccurate.
