### ISSUE TITLE
Regarding the necessity of the pure-white background

### ISSUE THREAD

**Issue by yitongx** [ShenhanQian/GaussianAvatars#29]
Hi,

Thanks for your good work. Really appreciate that you guys released the codes.

One thing I noticed is that you define the initial color of Gaussians to be some random color quite close to black (rather than randomly initialized), while the background color of your processed data is white. 

I'm not sure whether the high contrast between the initial Gaussian's color and the background color is beneficial for reducing the floaters near the mesh surface. Have you tried on the noisy background (non pure white) data before?

Thanks.

**Comment by ShenhanQian** [comment]
Hi, we didn't try rendering with noisy backgrounds. 

We observed that the periodic opacity resetting and gaussian pruning operation was already sufficient to remove floaters.

**Comment by yitongx** [comment]
One more thing, the head matting masks provided in your dataset are REALLY GOOD. Given that NeRSemble and GaussianAvatars share some mutual authors, I guess it's okay to ask here: 
Was the background removed during image capturing or post-processing (some procedure independent of the capturing)? If it was done during the post-processing, what methods did you use to achieve that fancy removal?

It would be great if you can share some ideas. Thanks.

**Comment by ShenhanQian** [comment]
As mentioned in Section B of the appendix, we use BackgroundMattingV2 for background removing. You can find our modified version [here](https://github.com/ShenhanQian/BackgroundMattingV2).

**Comment by yitongx** [comment]
Oh, thanks for the fast reply!
