### ISSUE TITLE
could you release data pre-process code? that would be helpful

### ISSUE THREAD

**Issue by doubi-killer** [ShenhanQian/GaussianAvatars#3]
I'm looking forward to your reply

**Comment by chendalao** [comment]
bro, would you know how to do with the data?

**Comment by sergidomenechguzy** [comment]
I would also be very interested in this, or at least some instruction steps to reproduce it on my own.

I want to create avatars with custom data and tried it using the basic COLMAP prior, but that didn't work well.
So being able to pre-process my data would be perfect.

**Comment by BingliangLi** [comment]
This is very important, there are so much potential in this work, so much follow ups can be built on it, so could you please release the pre-process code so people can make better use of this masterpiece? @ShenhanQian

**Comment by ShenhanQian** [comment]
We plan to share the pre-processing code after the paper is accepted. Please stay in tuned.

**Comment by naivenaive** [comment]
The pre-processing code would be of great help. Thank you in advance for providing it.

**Comment by ZiqiaoPeng** [comment]
Expect pre-processed code, which will greatly advance the progress of the community.

**Comment by sergidomenechguzy** [comment]
Is there any information on when the paper will be accepted and the pre-processing code released? Even a rough estimate would be appreciated as I'm working on a thesis with fixed deadlines and I need to decide if I wait or try to somehow reverse engineer it myself.

**Comment by nlml** [comment]
A hint for people in this thread: in our recent experiments, we find GaussianAvatars can be trained without the static offsets. Therefore you could likely use an existing available tracking method, e.g. https://github.com/Zielon/metrical-tracker , to achieve decent results already.

**Comment by BingliangLi** [comment]
> A hint for people in this thread: in our recent experiments, we find GaussianAvatars can be trained without the static offsets. Therefore you could likely use an existing available tracking method, e.g. https://github.com/Zielon/metrical-tracker , to achieve decent results already.

So we only need monocular video input like this paper? Could you please explain what is static offsets? Btw congrats for the paper!

**Comment by nlml** [comment]
Hmm monocular will be more tricky, I was suggesting these existing tracking methods could be extended to the multi-view setting. Static offsets are the per-vertex offsets added to FLAME, which are learned during the tracking stage of GaussianAvatars.

**Comment by jeb0813** [comment]
I'm trying to reproduce this work on other datasets, but there are few details about the customized photometric tracker, I cannot get correct flame params to carry on the experiment.

Are there any schedule to release the preprocessing code?

If the code is not yet ready, can you give some instruction steps or implementation details of the preprocess pipeline? @ShenhanQian 

(btw I recently read all paper accepted by cvpr24 on 3DGS HeadAvatar, this paper is the best of them all :octocat:

**Comment by YunShen66666** [comment]
> I'm trying to reproduce this work on other datasets, but there are few details about the customized photometric tracker, I cannot get correct flame params to carry on the experiment.
> 
> Are there any schedule to release the preprocessing code?
> 
> If the code is not yet ready, can you give some instruction steps or implementation details of the preprocess pipeline? @ShenhanQian
> 
> (btw I recently read all paper accepted by cvpr24 on 3DGS HeadAvatar, this paper is the best of them all :octocat:

hi, did you know how to combine the flame params and colmap params?  what's the orders to deal with colmap and flame?

**Comment by ShenhanQian** [comment]
Before we can release the preprocessing code, here is our note of camera conventions for your reference:

```
# Camera conventions

- NeRSemble raw data: OpenCV, world2camera
- Tracker:
    - dataloader: OpenCV, world2camera → OpenGL, world2camera
    - export: OpenGL, camera2world
- GaussianAvatars
    - dataloader: OpenGL, camera2world → OpenCV, world2camera
        - camera_info
            - R: world2cam.T
            - T: world2cam
        - camera
            - world_view_transform: world2cam.T
            - ProjectionMatrix: K.T
            - full_proj_transform: world2cam.T @ K.T
    - 3D-GS original remote viewer: OpenGL
    - remote viewer: OpenGL
    - local viewer: OpenCV
```

**Comment by jryebread** [comment]
@ShenhanQian please release the preprocessing code and instructions, thank you so much!

**Comment by ShenhanQian** [comment]
We have released a head tracking repository: https://github.com/ShenhanQian/VHAP. 
It is not the same as the original tracker, but the output can be directly used by GaussianAvatars.
