### ISSUE TITLE
How can I use colmap pose for training?

### ISSUE THREAD

**Issue by ZCB-endeavor** [ShenhanQian/GaussianAvatars#30]
Hi, thank you very much for your excellent work. I'm trying to use colmap pose for GaussianAvatars training, but the training results are not ideal. How can I handle the colmap pose to adapt to GaussianAvatars training?

I noticed that you have answered a similar question before, using Gram-Schmidt to process camera poses, but my training results did not align with the flame model, which felt like a scale factor was missing.

I'm looking forward to your reply !

**Comment by ShenhanQian** [comment]
Hi, our repo already supports datasets in COLMAP format after recent update. You can debug in two aspects:

1. The rendering results should be 3D-consistent in the viewer. You can take one or a few timesteps to optimize for a static scene without rigging to the mesh. To do so, you only need to remove `--bind_to_mesh` in the training command. This will indicate if the cameras are facing the right direction.

2. The mesh should align with rendered 3D Gaussians. You can check this by turning on "show mesh" in the viewer. If your mesh alignes with the image during tracking bot not under our framework. You may need to compare the difference in camera loading and processing. Some repo may scale up the mesh, but we keep the original scale.
