### ISSUE TITLE
About self-reenactment and cross-identity reenactment

### ISSUE THREAD

**Issue by Time-Lord12th** [ShenhanQian/GaussianAvatars#34]
Hi, dear author. I have some questions about self-reenactment and cross-identity reenactment.

1. For multi-view, the FLAME meshes have vertices at varied positions but share the same topology. Does that mean all the FLAME meshes have same number of vertices, and same number of triangles?
2. In checkpoint, there is only one set of 3DGS(for subject 306, after training, `gaussians.binding.shape = torch.Size([86127])`). Their 
location `µ`, rotation `r`, and anisotropic scaling `s` are all in the local space, right?
3. When I test self-reenactment or cross-identity reenactment, actually I'm modifying the parameters of the triangles, thereby altering the parameters of gs in the global space. This is consistent with the training process, so no additional optimization is needed, right?

I'm not very familiar with this field, so I really appreciate it if you could answer my questions!

**Comment by ShenhanQian** [comment]
Hi, for the questions
1. the topology is consistent, meaning the number of triangles and vertices remains the same. The only change is the positions of the vertices.
2. Yes.
3. Yes.

**Comment by Time-Lord12th** [comment]
Thanks for your answer, it helps a lot！
