### ISSUE TITLE
Discrepancy in net_type Option for `lpips()` between `train.py` and `metrics.py` 

### ISSUE THREAD

**Issue by HoYoung-City** [ShenhanQian/GaussianAvatars#35]
Hi!
I noticed an inconsistency in the calculation of the Metric in train.py.
The `lpips()` function is used without specifying the net_type option, as seen here:
https://github.com/ShenhanQian/GaussianAvatars/blob/f649a11bae59a1622500345b21641781f01fbab7/train.py#L296

Then, the default net_type for 'lpips()' is set to 'alex':
https://github.com/ShenhanQian/GaussianAvatars/blob/f649a11bae59a1622500345b21641781f01fbab7/lpipsPyTorch/__init__.py#L8

On the other hand, in metrics.py, the net_type for lpips() is set to 'vgg':
https://github.com/ShenhanQian/GaussianAvatars/blob/f649a11bae59a1622500345b21641781f01fbab7/metrics.py#L74

This discrepancy could explain why there are differences in the values.
I believe that using 'alex' might be the more appropriate option, as it is closer to the results presented in the paper.

Could you please confirm this?

Thank you for looking into this.

**Comment by ShenhanQian** [comment]
Hi, thanks for raising this question!

The reported numbers in our paper came from the evaluation in `train.py`, which means we used `alexnet` for LPIPS.

Meanwhile, we didn't use `metrics.py` but kept it in the repo, thinking it might be helpful in some use cases. Therefore, there can be some inconsistency.

BTW, did you get consistent numerical results from `metric.py` as those from `train.py` after moving to `alexnet`?

**Comment by HoYoung-City** [comment]
I used `alexnet` in `metric.py` , but I got different numerical results.

I haven't found the exact cause yet. It could be my mistake.

Thank you for your reply.
