### ISSUE TITLE
Unable to receive preprocessed data download verification code

### ISSUE THREAD

**Issue by xz0305** [ShenhanQian/GaussianAvatars#36]
The email address has been linked, but still cannot be received

**Comment by 3Der1999** [comment]
same problem here.

**Comment by ShenhanQian** [comment]
Please check your spam box if you get approval but cannot receive the verification code. Otherwise, you can resubmit a request with another email address while indicating the approved email.

**Comment by xz0305** [comment]
@ShenhanQian Request has been resubmitted

**Comment by ShenhanQian** [comment]
> @ShenhanQian Request has been resubmitted

Already approved

**Comment by xz0305** [comment]
changed my email but still can’t receive it.

**Comment by xz0305** [comment]
@ShenhanQian The problem still exists. Is there any solution? Thank you very much.

**Comment by ShenhanQian** [comment]
Hi @xz0305, I have given access to three different email addresses for you, including *@mail.hfut.edu.cn, *@hotmail.com, and *student.usm.my.

Did you get an notification of approval for any of them? How does the interface look like when you tried to get a verification code? Did you used the same email address?

**Comment by xz0305** [comment]
I haven't received the approval notification email yet. My interface looks like this
[cid:7dea58c7-47ef-4fff-8161-9f99cd520bdc]
________________________________
发件人: Shenhan Qian ***@***.***>
发送时间: 2024年4月17日 17:15
收件人: ShenhanQian/GaussianAvatars ***@***.***>
抄送: xz0305 ***@***.***>; Mention ***@***.***>
主题: Re: [ShenhanQian/GaussianAvatars] Unable to receive preprocessed data download verification code (Issue #36)


Hi @xz0305<https://github.com/xz0305>, I have given access to three different email addresses for you, including ***@***.***, ***@***.***, and *student.usm.my.

Did you get an notification of approval for any of them? How does the interface look like when you tried to get a verification code? Did you used the same email address?

―

**Comment by ShenhanQian** [comment]
We have added another choice for data downloading. Please refer to README.md for the link.

**Comment by xz0305** [comment]
very thankful

________________________________
发件人: Shenhan Qian ***@***.***>
发送时间: 2024年4月17日 22:29
收件人: ShenhanQian/GaussianAvatars ***@***.***>
抄送: xz0305 ***@***.***>; Mention ***@***.***>
主题: Re: [ShenhanQian/GaussianAvatars] Unable to receive preprocessed data download verification code (Issue #36)


We have added another choice for data downloading. Please refer to README.md for the link.

―
