### ISSUE TITLE
Managing gaussians.binding_counter in the function densify_and_split

### ISSUE THREAD

**Issue by seungjun-moon** [ShenhanQian/GaussianAvatars#4]
First of all, thank you for providing awesome results of your research.

I have a question about the function `densify_and_clone` in `scene/gaussian_model`.
<img width="968" alt="Screen Shot 2024-01-23 at 6 12 59 PM" src="https://github.com/ShenhanQian/GaussianAvatars/assets/26132224/858bf644-d0e9-45fc-8cd5-d96ad154cf4d">

Since we add the number of connections properly in line 466, I think the adding function at line 465 is redundant.
When I tried with my toy dataset, it occurs an undesirable discrepancy between the number of `self._xyz` and the sum of `self.binding_counter`.

When I wiped out line 465, it worked well.

If I missed something, please let me know.

Thank you.

**Comment by ShenhanQian** [comment]
Hi Seungjun, thanks for reporting this bug!

You are right, we should have removed that line. 
We have fixed this bug in the [latest commit](https://github.com/ShenhanQian/GaussianAvatars/commit/0fa776feac9ed782683eca977e132c64cdfe8682#).
