### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by wkxNiubi** [ShenhanQian/GaussianAvatars#42]
Hello author, sorry to bother you.
During the training step, I encountered the following problem：

Loading Test Cameras [27/04 15:01:33]
100%|█████████████████████████████████████| 2496/2496 [00:00<00:00, 4829.53it/s]
Number of points at initialisation:  10144 [27/04 15:01:36]
Training progress:   0%|                             | 0/600000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home1/stu/wkx/GaussianAvatars-main/train.py", line 350, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/home1/stu/wkx/GaussianAvatars-main/train.py", line 124, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, background)
  File "/home1/stu/wkx/GaussianAvatars-main/gaussian_renderer/__init__.py", line 86, in render
    rendered_image, radii = rasterizer(
ValueError: too many values to unpack (expected 2)
Training progress:   0%|                             | 0/600000 [00:40<?, ?it/s]

I followed the steps step by step, but where did the problem occur?
Could you please answer this question?

**Comment by ljwovo** [comment]
May I ask how you solved this problem back there?
