### ISSUE TITLE
release plan for customized photometric FLAME tracker

### ISSUE THREAD

**Issue by xiyichen** [ShenhanQian/GaussianAvatars#43]
Thanks for the excellent work and the code release. I am wondering if there's a plan to release the code for the "customized photometric tracker" as mentioned in [@5](https://github.com/ShenhanQian/GaussianAvatars/issues/5). I am interested in using it for some other works.

**Comment by ShenhanQian** [comment]
We have released a head tracking repository: https://github.com/ShenhanQian/VHAP. 
It is not the same as the original tracker, but the output can be directly used by GaussianAvatars.
