### ISSUE TITLE
[F glutil.cpp:332] eglGetDisplay() failed

### ISSUE THREAD

**Issue by psen2022** [ShenhanQian/GaussianAvatars#44]
(avatar) hci@hci:/workspace/psen/GaussianAvatars-main/GaussianAvatars-main$ SUBJECT=306
(avatar) hci@hci:/workspace/psen/GaussianAvatars-main/GaussianAvatars-main$ 
(avatar) hci@hci:/workspace/psen/GaussianAvatars-main/GaussianAvatars-main$ python train.py \
> -s /workspace/psen/GaussianAvatars-main/NeRSemble/306 \
> -m /workspace/psen/GaussianAvatars-main/output/306 \
> --port 60001 --eval --white_background --bind_to_mesh
Optimizing /workspace/psen/GaussianAvatars-main/output/306
Output folder: /workspace/psen/GaussianAvatars-main/output/306 [29/04 10:11:04]
[F glutil.cpp:332] eglGetDisplay() failed
Aborted (core dumped)
有这种问题的解决方案吗？

**Comment by ShenhanQian** [comment]
Please check if you have X11 and OpenGL set up correctly. Our program usually works fine when `xclock` and `glxgears` work.

**Comment by longyangqi** [comment]
> Please check if you have X11 and OpenGL set up correctly. Our program usually works fine when `xclock` and `glxgears` work.

I also face the problem when I try to run in a headless Linux server. After setting up X11 and OpenGL and using xvfb, i can run `xclock` and `glxgears`  without error(no output), but i still get the error: [F glutil.cpp:332] eglGetDisplay() failed when run the training.

**Comment by longyangqi** [comment]
> > Please check if you have X11 and OpenGL set up correctly. Our program usually works fine when `xclock` and `glxgears` work.
> 
> I also face the problem when I try to run in a headless Linux server. After setting up X11 and OpenGL and using xvfb, i can run `xclock` and `glxgears` without error(and no output due to using xvfb?), but i still get the error: [F glutil.cpp:332] eglGetDisplay() failed when run the training.

**Comment by ShenhanQian** [comment]
Which part of our repository gives you this problem?

**Comment by longyangqi** [comment]
> Which part of our repository makes you this problem?

Run training code:
>SUBJECT=306
>python train.py \
>-s data/UNION10_${SUBJECT}_EMO1234EXP234589_v16_DS2->0.5x_lmkSTAR_teethV3_SMOOTH_offsetS_whiteBg_maskBelowLine \
>-m output/UNION10EMOEXP_${SUBJECT}_eval_600k \
>--eval --bind_to_mesh --white_background --port 60000

And the output:
Optimizing output/UNION10EMOEXP_306_eval_600k
Output folder: output/UNION10EMOEXP_306_eval_600k [04/11 17:20:20]
[F glutil.cpp:332] eglGetDisplay() failed
Aborted (core dumped)

And just now, I switch to use dr.RasterizeCudaContext() in https://github.com/ShenhanQian/GaussianAvatars/blob/faf0b1311df3d99cb7da0e58a2f402d65850f77d/mesh_renderer/__init__.py#L29C1-L30C1. I can run successfully. But I do not know if it would affect the  training speed...
Thanks for your reply!

**Comment by ShenhanQian** [comment]
Thank you for reporting the problem and sharing the solution. The efficiency should be comparable. Now, we have made CUDA the default backend for nvdiffrast with the latest commit. You may want to upgrade to the latest version of nvdiffrast via
```
pip install nvdiffrast@git+https://github.com/ShenhanQian/nvdiffrast@backface-culling --force-reinstall
rm -r ~/.cache/torch_extensions/*/nvdiffrast*
```

**Comment by vemacular** [comment]
> > Which part of our repository makes you this problem?
> 
> Run training code:
> 
> > SUBJECT=306
> > python train.py 
> > -s data/UNION10_${SUBJECT}_EMO1234EXP234589_v16_DS2->0.5x_lmkSTAR_teethV3_SMOOTH_offsetS_whiteBg_maskBelowLine 
> > -m output/UNION10EMOEXP_${SUBJECT}_eval_600k 
> > --eval --bind_to_mesh --white_background --port 60000
> 
> And the output: Optimizing output/UNION10EMOEXP_306_eval_600k Output folder: output/UNION10EMOEXP_306_eval_600k [04/11 17:20:20] [F glutil.cpp:332] eglGetDisplay() failed Aborted (core dumped)
> 
> And just now, I switch to use dr.RasterizeCudaContext() in https://github.com/ShenhanQian/GaussianAvatars/blob/faf0b1311df3d99cb7da0e58a2f402d65850f77d/mesh_renderer/__init__.py#L29C1-L30C1. I can run successfully. But I do not know if it would affect the training speed... Thanks for your reply!

I made the above modifications by replacing gl with CUDA, and it successfully ran.
