### ISSUE TITLE
cx cy，question

### ISSUE THREAD

**Issue by SSground** [ShenhanQian/GaussianAvatars#45]
I found a problem, when cx,cy are not in the center of the image, the projection is wrong.

**Comment by ShenhanQian** [comment]
You are right. The currnet code assumes the optical center to lie at the center of the image and only loads FoV from the camera parameters.

**Comment by SSground** [comment]
> You are right. The currnet code assumes the optical center to lie at the center of the image and only loads FoV from the camera parameters.

Thanks.
