### ISSUE TITLE
dynamic_offset

### ISSUE THREAD

**Issue by aixiaodewugege** [ShenhanQian/GaussianAvatars#46]
Thanks for your brilliant work! I have a few questions.
What is dynamic_offset? And why it is set to None by default?

**Comment by ShenhanQian** [comment]
Hi, `dynamic_offset` is a per-timestep vertex offset of the mesh vertices. It's not included in our final method and is disabled by diffault. You can simply ignore it.

**Comment by aixiaodewugege** [comment]
Thanks for your reply! Does static_offset mean a fix for the person in canonical space? Because the Flame tracker is not correct?

**Comment by ShenhanQian** [comment]
Hi!
No, static_offset is obtained during FLAME tracking. It modifies vertex positions in the canonical space of FLAME to better align to regions like hair.

However, the static_offset is not mandatory, which means GaussianAvatars can also run well on tracking results without a static_offset.

**Comment by aixiaodewugege** [comment]
Thanks!  Could you please tell me which foreground model you used? I noticed that the mask you generated is very accurate.

**Comment by ShenhanQian** [comment]
Hi, we refer to the model in the section "Appendix B Dataset Division" in our paper.
