### ISSUE TITLE
Fixing the index of 133-th teeth face

### ISSUE THREAD

**Issue by seungjun-moon** [ShenhanQian/GaussianAvatars#50]
<img width="1021" alt="teeth" src="https://github.com/ShenhanQian/GaussianAvatars/assets/26132224/4c93f35c-846b-4a6d-9076-2e0cac956256">

Hello. Thank you for providing your awesome research!

I suggest that a vertex index in face number 10109 can be fixed.

In the function add_teeth(), you define 133-th face of teeth (=133+9976 = 10109-th face of FLAME) as below, in the 444-th line of the file `flame_head/flame.py` :

`[101, 116, 114],  # 133`

However, this returns an unexpected face as shown above.

I suggest that we can fix it to `[101, 116, 115],  # 133` 

Thank you.

**Comment by ShenhanQian** [comment]
Hi SeungJun, thanks for reporting this issue!

We confirm that face #133 has a false vertex as shown below:
![snapshot01-1](https://github.com/ShenhanQian/GaussianAvatars/assets/23174052/0e2b3645-b202-4846-9c57-f2cb099c27d7)
 
As you proposed, the vertices of face #133 should be changed to `[101, 116, 115],  # 133`. 
Our early document also supports this fix:
![image](https://github.com/ShenhanQian/GaussianAvatars/assets/23174052/dce56671-5a6c-4394-a98d-2ee1c2dfbf51)

Thanks again for sharing!
