### ISSUE TITLE
RAM question

### ISSUE THREAD

**Issue by SSground** [ShenhanQian/GaussianAvatars#51]
Hi,sir
I initialized 40,000 vertices. As training increases, my memory will continue to increase until it exceeds the upper limit of 32G. What should I do to avoid this phenomenon?

**Comment by ShenhanQian** [comment]
Hi, you may check if Out-of-Memory is caused by the growing number of points. If so, you can turn off adding new points once their number exceeds a threshold.

**Comment by SSground** [comment]
> Hi, you may check if Out-of-Memory is caused by the growing number of points. If so, you can turn off adding new points once their number exceeds a threshold.

Thank you for your prompt reply, but it doesn't seem to be an issue with the increase in point clouds, as I only have 50000 point clouds, and after killing them, I used start checkpoint again to continue training without encountering this issue. The error seems to be an issue with the dataloader
![image](https://github.com/ShenhanQian/GaussianAvatars/assets/27821863/7803d658-4aaa-4b30-8bae-f6e83694dce0)

**Comment by ShenhanQian** [comment]
I see. You may check if you cache images and other large data in __getitem__() of the dataset. Ideally, your memory usage should stay the same from the beginning to the end of the optimization.

**Comment by SSground** [comment]
> I see. You may check if you cache images and other large data in **getitem**() of the dataset. Ideally, your memory usage should stay the same from the beginning to the end of the optimization.

My every iteration is the same, but it seems that every 3000 or 1000 times, a few hundred MB of memory will be added.
![image](https://github.com/ShenhanQian/GaussianAvatars/assets/27821863/b0d3b2bb-cb81-4dc5-b78a-77c4265a50cf)

**Comment by XvHaidong** [comment]
@SSground Hello, I met the same issue with you, do you know how to solve it? Thank you so much!
