### ISSUE TITLE
Installation Issue: Unable to Install Submodules

### ISSUE THREAD

**Issue by BedirYilmaz** [ShenhanQian/GaussianAvatars#52]
Encountered a problem while attempting to install supporting libraries via the command:

`$ pip install -r requirements.txt`
```
ERROR: The directory 'submodules/diff-gaussian-rasterization' cannot be installed.
Neither a 'setup.py' nor 'pyproject.toml' file was found.
```
SETUP DETAILS:

- Operating System: Ubuntu 22.04
- CUDA Version: 11.8
- Torch Version: 2.3

Note: During the installation of Torch and torchvision, a specific CUDA version (cuda118) was specified due to compatibility issues. The installation commands used were:

```
$ pip install ninja
$ pip install torch torchvision --index-url https://download.pytorch.org/whl/cu118
```

**Comment by ShenhanQian** [comment]
Please check if you have appended `--recursive` to the command when you clone our repository:
`git clone https://github.com/ShenhanQian/GaussianAvatars.git --recursive`
