### ISSUE TITLE
Weird xyz loss in custom data

### ISSUE THREAD

**Issue by aixiaodewugege** [ShenhanQian/GaussianAvatars#53]
![image](https://github.com/ShenhanQian/GaussianAvatars/assets/47085237/193c1810-5611-40a5-a6a5-28d7841e7f36)
The XYZ loss is always 0, and the scale loss is five times larger than in your data. Do you know what could be causing this? I use the monocular camera data for training.

**Comment by aixiaodewugege** [comment]
Thanks for your reply!
![image](https://github.com/ShenhanQian/GaussianAvatars/assets/47085237/ffd01c24-c0fb-4061-9649-5f002961336a)
Looks like the R T are not working for Flame model?
To use the method in monocular camera data, I just set the R T for camera are ones and zeros. But I think there is some problem.

**Comment by aixiaodewugege** [comment]
Thanks for your reply!
![image](https://github.com/ShenhanQian/GaussianAvatars/assets/47085237/c6494ecd-ff4a-4409-8902-74799711b7fd)

Here is my result. I use the R T from monocular camera flame tracker, and set it as camera pose. And I set the flame R and T to ones and zeros. Am I handle it right?

**Comment by longyangqi** [comment]
> Thanks for your reply! ![image](https://private-user-images.githubusercontent.com/47085237/330072240-c6494ecd-ff4a-4409-8902-74799711b7fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NzMwOTcsIm5iZiI6MTczMDc3Mjc5NywicGF0aCI6Ii80NzA4NTIzNy8zMzAwNzIyNDAtYzY0OTRlY2QtZmY0YS00NDA5LTg5MDItNzQ3OTk3MTFiN2ZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDAyMTMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMmYwMDZkNGFmYTk1MzY2MGEwMDk3MmY0MTdhNWZiMzUwNThiNGM2OWUzMWI2ZTZkMzFkZTZiNzNhZTliMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2g0uqM6hORldO6KDMyUQe0P4vJOc9vA_kVoDi8vpefA)
> 
> Here is my result. I use the R T from monocular camera flame tracker, and set it as camera pose. And I set the flame R and T to ones and zeros. Am I handle it right?

Did you get correct results by the operations on camera pose?
