### ISSUE TITLE
About GS binding mesh

### ISSUE THREAD

**Issue by HaoZhiG** [ShenhanQian/GaussianAvatars#55]
Hello! It's an excellent work! While reading through the code, I noticed there are methods for not binding GS to the mesh. Is it possible to reproduce the results without binding to the mesh?

**Comment by ShenhanQian** [comment]
Hi! Without binding the mesh, the method degrades to vanilla 3D-GS, which only handles the static scene reconstruction.

**Comment by HaoZhiG** [comment]
Thank you for your response！
