### ISSUE TITLE
mesh of the Head

### ISSUE THREAD

**Issue by Zvyozdo4ka** [ShenhanQian/GaussianAvatars#59]
thank you for publishing code.

1. Is it possible to extract the FLAME mesh along with the Gaussian parameters directly from a video input using the GaussianAvatars method?

2. Can a point cloud representation be generated from the Gaussian parameters obtained through this method?

**Comment by ShenhanQian** [comment]
Hi, thanks for your questions.

1. Theoratically, it is possible because both GaussianAvatars and NVDiffRast can backpropagate gradients to vertices. But it may take some engineering effort.
2. Yes, you can directly take the positions of 3D Gaussians to form a point cloud.
