### ISSUE TITLE
Can you provide an example for testing?

### ISSUE THREAD

**Issue by llmgpt** [ShenhanQian/GaussianAvatars#61]
Are pre-trained weights not provided? I just want to do inference, do I need to retrain? Because the dataset download is too large, other environments are configured.

**Comment by ShenhanQian** [comment]
Hi, you can push the latest commit and try the [demo](https://github.com/ShenhanQian/GaussianAvatars/tree/main#0-demo) now.

**Comment by llmgpt** [comment]
Thank you, I have successfully run the example.
