### ISSUE TITLE
illegal memory access with adaptive density control

### ISSUE THREAD

**Issue by GuangyuWang99** [ShenhanQian/GaussianAvatars#62]
Thanks for your great work! 

I re-implement a mesh-bounded 3d gaussian representation that **strictly follows the implementations in [`gaussian_model.py`](https://github.com/ShenhanQian/GaussianAvatars/blob/main/scene/gaussian_model.py)**. I implement my own mesh loading script with the same logic as in [`flame_gaussian_model.py`](https://github.com/ShenhanQian/GaussianAvatars/blob/main/scene/flame_gaussian_model.py), and all the other codes and the environments are the same as [3d-gaussian-splatting](https://github.com/graphdeco-inria/gaussian-splatting).

However, the following error will be raised during rendering ([`render_pkg = render(viewpoint_cam, gaussians, pipe, background)`](https://github.com/ShenhanQian/GaussianAvatars/blob/main/train.py#L124))at the iteration **after the very first adaptive density control operation** ([`gaussians.densify_and_prune()`](https://github.com/ShenhanQian/GaussianAvatars/blob/main/train.py#L202)):

```bash
File "train.py", line 91, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, bg)
File ".../gaussian_renderer/__init__.py", line 99, in render
    "visibility_filter": radii > 0,
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

If the adaptive density control is disabled, e.g., by setting `densify_from_iter` and `densification_interval` to a very large value, it will be running correctly. 

I'm wondering have you ever seen the same problem? Thanks in advance!

**Comment by ShenhanQian** [comment]
I haven't met the same problem. You can try commenting out "split", "clone", and "prune" one at a time to locate the bug.

**Comment by GuangyuWang99** [comment]
Thanks again for your prompt reply!
