### ISSUE TITLE
albedo sharing

### ISSUE THREAD

**Issue by andyl-flwls** [ShenhanQian/GaussianAvatars#66]
Hi, can you share the albedo of the first image for 306?

**Comment by ShenhanQian** [comment]
Sorry, I don't get which part are you refering to since this project does not use or produce an albedo map.

**Comment by andyl-flwls** [comment]
sry for the inconvince, probably i should ask this question under vhap. I found out the albedo for monocular tracking is very good, and albedo is much better than that from mica tracking. (seems like you did not optimize flame texture but directly rgb channels) Due to that dataset for subject 306 is too large and tracking is a little bit time consuming, may i request the albedo map for 306 (if you have one saved in your workstation). If you donot have one, i will try to find some machines and do tracking myself again.

**Comment by ShenhanQian** [comment]
The file is temporally available and will removed soon.
![frame_00000](https://github.com/user-attachments/assets/d0f3adc6-b7fe-4631-97fd-a4acba99e8a9)

**Comment by andyl-flwls** [comment]
Really appreciate your help!!!
