### ISSUE TITLE
How to add eyelids parameters to flame_param?

### ISSUE THREAD

**Issue by ZCB-endeavor** [ShenhanQian/GaussianAvatars#71]
Hi, thank you for your great work.

I would like to know how to add eyelids parameters to the flame parameter. 

`# unions
...

 self.v.register_buffer("eyelids", torch.cat([self.v.left_eyelid, self.v.right_eyelid]))
 self.v.register_buffer("lip_inside_ring", torch.cat([self.v.lip_inside_ring_upper, self.v.lip_inside_ring_lower, torch.tensor([1594, 2730])]))`

I've noticed that there is a definition of the eyelid region in the flame.py, but I didn't know how to use my eyelids parameters to drive the model. 

The shape of my eyelids parameter is torch. Size([1, 2]).

I'm looking forward to your reply!

**Comment by ShenhanQian** [comment]
Hi, eyelid movement is coverd in the expression space of FLAME in an implicit way. This means you do not have a direct control over eyelids. 
You may look at which expression blendshapes contribute to the eyelid vertices. Or, you can add your own blendshape for eyelids.

**Comment by ZCB-endeavor** [comment]
I tried to add eyelids parameters to control the offset of vertices in the flame.py, and after testing, it seems to have some effect on the driving of the eyelids. Thanks for your reply!
