### ISSUE TITLE
How to model hair using FLAME

### ISSUE THREAD

**Issue by shi-yan** [ShenhanQian/GaussianAvatars#73]
Hello,

Thank you very much for this paper! I'm puzzled by the images used in the paper, because , as we know, FLAME can't model hair, whereas the proxy models in the paper has hair geometry. The paper doesn't seem to mention how hair geometry was generated?

Thank you!

**Comment by ShenhanQian** [comment]
Hi, the hair is captured by applying a per-vertex offset. This offset is determined during the [FLAME tracking](https://github.com/ShenhanQian/VHAP) process using photometric optimization.

**Comment by shi-yan** [comment]
Thank you very much!
