### ISSUE TITLE
Issue with Uneven Brightness on Avatar Faces with Viewpoint Changes

### ISSUE THREAD

**Issue by Jp-17** [ShenhanQian/GaussianAvatars#75]
Hello Shenhan!

 After training avatars using VHAP/Gaussian-avatars with our own dataset, we noticed an issue where the facial regions of the avatars exhibit uneven brightness that changes with the viewpoint. It gives the impression of inconsistent brightness distribution (please refer to the attached video for an example).

Based on your experience, do you know what might be causing this issue? Are there any potential directions we can explore to optimize and mitigate this problem?

**Additional Information**:

During training, I set sh=0 in the command, so I think this issue is not caused by spherical harmonics affecting the shading with viewpoint changes.
I also added an additional regularization term in the GaussianAvatars loss, which encourages the opacity values to converge toward 0 or 1 (to enforce binary opacity).

Any insights or suggestions would be greatly appreciated!

Thank you in advance!

https://github.com/user-attachments/assets/78af3d13-39b8-4c82-a7c1-c9a6f1066239

**Comment by ShenhanQian** [comment]
Hi Peng, thanks for sharing your latest result!

I have observed similar effects: some part of the face looks opaque from the front but semi-transparent from the sides. The popping effect is also observable. They are related to the fact that 3dGS is not completely view-consistent - the perspective projection of 3D Gaussian to the screen space is an imperfect approximation. In contrast, 2DGS may do a better job of representing a surface, as shown in this example: https://colab.research.google.com/drive/1qoclD7HJ3-o0O1R8cvV3PxLhoDCMsH8W?usp=sharing.

**Comment by Jp-17** [comment]
Thank you for your quick response!

I’d like to confirm two things for better understanding:

1. I’m not very familiar with 2DGS. If we modify the Gaussian-Avatars pipeline to incorporate 2DGS-related logic, would it still be possible to render dynamic visualizations of Gaussian-Avatars using a similar rendering pipeline to the original implementation? Also, would this require a specialized viewer tailored for 2DGS?

2. Regarding "the perspective projection of 3D Gaussian to the screen space is an imperfect approximation," besides 2DGS, do you think methods like [SuGaR](https://arxiv.org/pdf/2311.12775), which make the Gaussians flatter and better aligned with the surface, could help alleviate this issue?

Thanks again for your insights and suggestions!

**Comment by ShenhanQian** [comment]
1. Yes. Based on the `gsplat` branch of GaussianAvatars, it should be easy to switch to 2DGS. Basically, you only change the 3D representation and rasterizer. The viewer is independent of the changes since it just takes a rendered image given a camera pose.
2. SuGaR is still 3DGS, just bound to meshes rigidly. It will still suffer from the perspective artifacts even if made flat, as shown in this example: https://colab.research.google.com/drive/1qoclD7HJ3-o0O1R8cvV3PxLhoDCMsH8W?usp=sharing.

**Comment by Jp-17** [comment]
Got it, thank you! I'll learn it and try!

**Comment by longyangqi** [comment]
Hello, have you tried 2D GS?
I may face a similar issue, when trained on my own data.
And the transparent issue is especially evident in the nose region.
(due to privacy,  I only provide the nose part to show the issue)
some views are ok while some views become transparent 
<img src="https://github.com/user-attachments/assets/123d4151-3c10-4deb-8e49-4283afb0cb2f" alt="image" height="300"/>----<img src="https://github.com/user-attachments/assets/3a221623-64de-42c5-89ef-769319e589d9" alt="image" height="300"/>
@ShenhanQian @Jp-17 Based on your experience, do you have any suggestions to mitigate this problem?

**Comment by Jp-17** [comment]
> Hello, have you tried 2D GS? I may face a similar issue, when trained on my own data. And the transparent issue is especially evident in the nose region. (due to privacy, I only provide the nose part to show the issue) some views are ok while some views become transparent <img alt="image" height="300" src="https://private-user-images.githubusercontent.com/13297107/402924945-123d4151-3c10-4deb-8e49-4283afb0cb2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc0NjEzNTMsIm5iZiI6MTczNzQ2MTA1MywicGF0aCI6Ii8xMzI5NzEwNy80MDI5MjQ5NDUtMTIzZDQxNTEtM2MxMC00ZGViLThlNDktNDI4M2FmYjBjYjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTIxVDEyMDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzN2E1NzhmODZiZGQ1ZjIxYjg2YmIzNDA1Mjc1NWNjZWY3MDc1OTFmNTNkMjE5Nzk2ZDI2YWU0OGJjMTI3MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yLFt3axyWwcDrncv0fwVlHPLN-WG187iez0rmfrupsQ">----<img alt="image" height="300" src="https://private-user-images.githubusercontent.com/13297107/402925091-3a221623-64de-42c5-89ef-769319e589d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc0NjEzNTMsIm5iZiI6MTczNzQ2MTA1MywicGF0aCI6Ii8xMzI5NzEwNy80MDI5MjUwOTEtM2EyMjE2MjMtNjRkZS00MmM1LTg5ZWYtNzY5MzE5ZTU4OWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTIxVDEyMDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZjJhOGE1ZmVhYzg5NDA5OGViZjRjZjEyYzA2NzliOGMwNWMzNzZiYWU5NDNkNzM4MzZkOWI1MmU4MWUyNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RnrqO6lIoblJdxFAkKeKtWu-mLB94MnEnGFG82fWQAM"> [@ShenhanQian](https://github.com/ShenhanQian) [@Jp-17](https://github.com/Jp-17) Based on your experience, do you have any suggestions to mitigate this problem?

You could try introducing regularization on opacity to partially mitigate the "transparent hole" issue. Additionally, in our experiments, adjusting the overall brightness of the dataset slightly improved the inconsistent transparency (though we’re not entirely sure why). For now, this gave us acceptable results, so we haven’t yet explored the 2D GS approach. If you make further progress, feel free to share—we’d love to collaborate and exchange ideas!

**Comment by longyangqi** [comment]
> You could try introducing regularization on opacity to partially mitigate the "transparent hole" issue. Additionally, in our experiments, adjusting the overall brightness of the dataset slightly improved the inconsistent transparency (though we’re not entirely sure why). For now, this gave us acceptable results, so we haven’t yet explored the 2D GS approach. If you make further progress, feel free to share—we’d love to collaborate and exchange ideas!
Thanks for your reply!
As for adjusting the overall brightness, could you provide more details? Did you increase or reduce the brightness or align the brightness to some values?

**Comment by Jp-17** [comment]
Hello, the characters we captured earlier were too dark, so we increased the overall brightness of the video using Adobe PR. At the same time, we combined regularization for opacity, which slightly improved the results. However, we believe this is only a temporary compromise and not a fundamental solution to the problem.

**Comment by Jp-17** [comment]
Add one thing, I noticed that the brightness variations in the scene might be closely related to the distribution/density of 3D Gaussian Splatting (3DGS) points. In regions with significant brightness changes, the point cloud appears notably sparser or even scarce.

What improvements could be made to enhance both the density and spatial uniformity of 3DGS points, especially in these problematic regions? Are there specific strategies or parameter adjustments to address this issue?

Hope to hear your advice! @ShenhanQian @longyangqi 

By the way, Happy Chinese New Year!

**Comment by ShenhanQian** [comment]
Hi, I think the problem is related to the constantly white background color. 

Let's consider a moment when the target pixel is brighter than the current rendering. There are independent ways to minimize photometric error:
1. Making the corresponding splat brighter.
2. Making the corresponding splat more transparent.

You will have the same problem if you set the background color to black or any other constant color. As a remedy, you can try changing the background color for each iteration. Make sure that you change it for both the GT image and the renderer.

Happy Chinese New Year to you, too!
