### ISSUE TITLE
Why are the pre-processed camera extrinsic parameters different from those in the original NeRSemble dataset?

### ISSUE THREAD

**Issue by zydmu123** [ShenhanQian/GaussianAvatars#9]
I'd like to know if there is any special adjustment mode to the camera? Thanks a lot!

**Comment by zydmu123** [comment]
Thanks for your kind reply!@ShenhanQian As you mentioned above，the pre-processed camera extrinsic parameters have been matched with the FLAME mesh after the tracking process. However, it seems still a slight issue converting your preprocessed camera parameters into a pytorch3d's format. Here is my test, by trying this code I can't get the normal matched results through a PerspectiveCameras, did I miss something important? 
![GS_t](https://github.com/ShenhanQian/GaussianAvatars/assets/111970347/e842a790-131e-4e23-8bcb-633b25f13f30)

**Comment by zydmu123** [comment]
It works, Thanks a lot!

**Comment by SSground** [comment]
> Hi, the extrinsics of raw NeRSemble are camera2world in the **OpenCV** convention, obtained from COLMAP.
> 
> Before FLAME tracking, we convert the extrinsics into camera2world in the **OpenGL** convention, the same as most synthetic NeRF datasets.
> 
> We also apply **a global rotation** to all cameras to align their mean pose with the world coordinate.
> 
> ```python
> def align_cameras_to_axes(
>     R: torch.Tensor,
>     T: torch.Tensor,
>     target_convention: Literal["opengl", "opencv"] = None,
> ):
>     """align the averaged axes of cameras with the world axes.
> 
>     Args:
>         R: rotation matrix (N, 3, 3)
>         T: translation vector (N, 3)
>     """
>     # The column vectors of R are the basis vectors of each camera.
>     # We construct new bases by taking the mean directions of axes, then use Gram-Schmidt
>     # process to make them orthonormal
>     bases_c2w = gram_schmidt_orthogonalization(R.mean(0))
>     if target_convention == "opengl":
>         bases_c2w[:, [1, 2]] *= -1  # flip y and z axes
>     elif target_convention == "opencv":
>         pass
>     bases_w2c = bases_c2w.t()
> 
>     # convert the camera poses into the new coordinate system
>     R = bases_w2c[None, ...] @ R
>     T = bases_w2c[None, ...] @ T
>     return R, T
> ```
> 
> After we get FLAME tracking results, we add **a global translation** to all cameras and the FLAME mesh so that the mean position of the head in each sequence is at the origin.

I used the metahuman model. Is it necessary to put the model at the original point?
